### ISSUE TITLE
#.i + 1

### ISSUE THREAD

**Issue by hons82** [mulle-kybernetik/MulleScion#6]
I've a template with this content

```
<!--
        {% for articleShortDO in accessoryItems %}
            {% if articleShortDO#.i < 12 %}
        -->
<div name="crossSelling" id="crossSelling{{ articleShortDO#.i + 1 }}" class="crossSelling">
<div class="crossSellingTop">
<p>{{ articleShortDO.description_short }}</p>
</div>
</div>
<!--
            {% endif %}
        {% endfor %}
        -->
```

I've simplified it, so I hope it is still syntactically correct.

The parser is giving me an error at the _{{ articleShortDO#.i + 1 }}_ telling me that instead of the _+_ he's expecting _}}_

I'll start to search for a solution... Maybe you can give me a hint where the error could be...

**Comment by codeon-nat** [comment]
Checkout Limitations in the README.md:

```
MulleScion does not do arithmetic or bitwise logic, quite on purpose.
```

In case of `+ 1` you could experiment with placing a category on **NSNumber**. Like this, it probably works:

```
@implementation NSNumber (SimpleArithmetic)

- (NSInteger) postIncrementedIntegerValue
{
   return( [self integerValue] + 1);
}

@end
```

and say `articleShortDO#.i.postIncrementedIntegerValue`.
Or

```
foo = articleShortDO#.i
foo = foo.postIncrementedIntegerValue
```

**Comment by codeon-nat** [comment]
As an alternative checkout [`-renderInto:localVariables:dataSource:`](https://github.com/mulle-nat/MulleScion/blob/release/src/MulleScionObjectModel%2BPrinting.m#L1597) in `MulleScionFor( Printing)`.

```
      [info setObject:[NSNumber numberWithInteger:i]
               forKey:@"i"];
```

You could add:

```
      [info setObject:[NSNumber numberWithInteger:i + 1]
               forKey:@"nexti"];
      [info setObject:[NSNumber numberWithInteger:i - 1]
               forKey:@"previ"];
```

and then say `#.nexti`

**Comment by hons82** [comment]
Wow. Thanks a lot for the fast answers.
Actually I'm quite new in the project and did not explore everything yet.
I've seen that you asked in a comment if the #i is a custom implementation... I'm not sure about it, but I'll check... However that part seems to be acepted by the parsers.

For the plus1 I'll try with your suggestions. Thx

**Comment by mulle-nat** [comment]
Well please ignore that previous (redacted) comment, I forgot about the [for](https://github.com/mulle-nat/MulleScion/blob/release/dox/for.scion) special variables. :)

**Comment by hons82** [comment]
Good! So That's where it comes from 😁

**Comment by mulle-nat** [comment]
I think the nexti, previ thing I will just put into MulleScion myself. (It's been pushed to the development repository)
