### ISSUE TITLE
Use <objc></objc> for code ?

### ISSUE THREAD

**Issue by mulle-nat** [mulle-kybernetik/MulleScion#7]
The idea isn't mine. I stole it from this [article](https://dev.to/nullvoxpopuli/the-emberjs-of-the-future-today-12c) about ember. But the advantage is that most of the page could be formatted with HTML pretty printing and editing would be easier.

**Comment by mulle-nat** [comment]
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html lang="de">
<head>
 <style type="text/css">
 objc { display: none; white-space: pre; }
</style>
</head>


<body>
   <h1> Hello</h1>

   Some Text

   <objc>
      [[Foo new] whatever];
  </objc>
   More text

   Final text
   <pre>
      Do not
         reformat
            me reindenter
   </pre>
</body>

</html>
```

This works in as much, as that objc is hidden, even if noone is interpreting the contents.

**Comment by mulle-nat** [comment]
One problem is that the inside of &lt;objc&gt; (and &lt;pre&gt;) for that matter does not get properly reindented.

Indent could be preserved like so:

```

   <objc>
      if YES
      then
      <objc>
         [[Foo new] whatever];
      </objc>
      endif
   </objc>
```

But it's kinda verbose and not that readable.

**Comment by mulle-nat** [comment]
Conceivably one could add keyword tags also:

```
<if>
<else/>
</if>
<while>
</while>
<for>
</for>
```
They would be stripped out anyway during MulleScion processing. Hmmm... 

> The else thing doesn't lend itself well to formatting though, or ?

**Comment by codeon-nat** [comment]
@denunv Was meinste dazu ?

**Comment by mulle-nat** [comment]
VS Code formats it like this:

<img width="265" alt="grafik" src="https://user-images.githubusercontent.com/1381995/46481006-adff4180-c7f2-11e8-8439-e1cfc1a71ad8.png">

Which looks fine by me (except for the else, but that's probably unsolvable). But there is no code yet.

**Comment by mulle-nat** [comment]
```
<block>
<block/>
```

If possibly also needed.

**Comment by mulle-nat** [comment]
This is now a separate project: [MulleScionHTMLPreprocessor](https://github.com/mulle-nat/MulleScionHTMLPreprocessor)
